const LinkedList = require("./linkedList.js");
const list = new LinkedList();
list.push(15);
list.push(10);
list.push(12);
const temp = list.getElementAt(1);
console.log(temp);
list.insert(5, 1);
const temp1 = list.getElementAt(1);
console.log(temp1);